---
- hosts: factorio
  user: root
  handlers:
    - include: handlers/main.yml
  tasks:
    - include: tasks/configs.yml
    - include: tasks/network.yml
    - include: tasks/security.yml
    - include: tasks/application.yml
  roles: 
    - { role: factorio-server}
    
# {{ ansible_eth0.ipv4.address }}
