---
- name: Disable password-login for the root
  lineinfile:
    dest:   /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    line: 'PermitRootLogin without-password'
    state: present
    backrefs: yes
  notify: Restart sshd


- name: Disable X11Forwarding
  lineinfile:
    dest:   /etc/ssh/sshd_config
    regexp: '^X11Forwarding yes'
    line: 'X11Forwarding no'
    state: present
    backrefs: yes
  notify: Restart sshd

- name: Install fail2ban
  yum:
    name: "fail2ban"
    state: present

- name: Upload fail2ban config
  template:
    src: templates/fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/customisation.local
    owner: root
    mode: 0644
  notify: Restart fail2ban
