---
# tasks file for factorio-server
- name: Make sure Factorio server paths exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ factorio.root_path }}/archive"
    - "{{ factorio.root_path }}/servers"

- name: Create Factorio server group
  group:
    name: "{{ factorio.user.group }}"
    state: present

- name: Populate skeleton folder for users
  file:
    path: /etc/skel/{{ item }}
    state: directory
  with_items:
    - mods
    - saves

- name: Create Factorio server user
  user:
    name: "{{ factorio.user.name }}"
    group: "{{ factorio.user.group }}"
    home: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}"
    state: present

- name: Setup Factorio server folder permissions
  file:
    path: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}"
    mode: "0750"
    recurse: yes

- name: Install requirements
  package:
    name: "{{item}}"
    state: present
  with_items:
    - "{{ factorio.dependencies }}"

- name: Download Factorio server packages
  get_url:
    url:  "{{ factorio.package.url }}"
    dest: "{{ factorio.root_path }}/archive/{{ factorio.package.name }}"

- name: Create target directory for server package
  file:
    path: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}"
    state: directory
  become_user: "{{ factorio.user.name }}"
  become: true

- name: Unarchive server package
  unarchive:
    src: "{{ factorio.root_path }}/archive/factorio_headless_x64_{{ factorio.package.version }}.tar.gz"
    dest: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}"
    extra_opts: ['--strip-components=1']
    copy: no
  become_user: "{{ factorio.user.name }}"
  become: true

- name: Upload server-settings
  template:
    src: server-settings-example-{{ factorio.package.version }}.json.j2
    dest: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}/data/server-settings.json"
  become_user: "{{ factorio.user.name }}"
  become: true

- name: Upload map-gen-settings
  template:
    src: map-gen-settings.example-{{ factorio.package.version }}.json.j2
    dest: "{{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}/data/map-gen-settings.json"
  become_user: "{{ factorio.user.name }}"
  become: true

- name: Set server parameters for first start
  set_fact:
    factorio_server_parameters: "--server-settings {{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}/data/server-settings.json --start-server"
  when: factorio.new_map

- name: Set server parameters for later starts
  set_fact:
    factorio_server_parameters: "--server-settings {{ factorio.root_path }}/servers/{{ factorio.user.name }}/{{ factorio.package.version }}/data/server-settings.json --start-server /opt/servers/factorio/saves/test.zip"
  when: not factorio.new_map

- name: Upload systemd service
  template:
    src: factorio-server-{{ factorio.package.version }}.service.j2
    dest: "/etc/systemd/system/factorio-server-{{ factorio.user.name }}-{{ factorio.package.version }}.service"
    mode: 0644