---
# tasks file for factorio-server
- name: Make sure Factorio Server paths exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ factorio.root_path }}/archive"
    - "{{ factorio.root_path }}/servers"

- name: Create Factorio Server group
  group:
    name: "{{ item.value.group }}"
    state: present
  with_dict: "{{ factorio.users }}"

- name: Populate Skeleton folder for users
  file:
    path: /etc/skel/{{ item }}
    state: directory
  with_items:
    - mods
    - saves

- name: Create Factorio Server users
  user:
    name: "{{ item.key }}"
    group: "{{ item.value.group }}"
    home: "{{ factorio.root_path }}/servers/{{ item.key }}"
    state: present
  with_dict: "{{ factorio.users }}"

- name: Setup Factorio Server folder permissions
  file:
    path: "{{ factorio.root_path }}/servers/{{ item.key }}"
    mode: "0750"
  with_dict: "{{ factorio.users }}"

- name: Install requirements
  package:
    name: "{{item}}"
    state: present
  with_items:
    - "{{ factorio.dependencies }}"

- name: Download Factorio Server packages
  get_url:
    url:  "{{ item.value.url }}"
    dest: "{{ factorio.root_path }}/archive/{{ item.value.name }}"
  with_dict: "{{ factorio.packages }}"

- name: Create target directory for Server package
  file:
    path: "{{ factorio.root_path }}/servers/{{ item.key }}/{{ item.value.version }}"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ factorio.users }}"

- name: Unarchive Desired Server Packages
  unarchive:
    src: "{{ factorio.root_path }}/archive/factorio_headless_x64_{{ item.value.version }}.tar.gz"
    dest: "{{ factorio.root_path }}/servers/{{ item.key }}/{{ item.value.version }}"
    extra_opts: ['--strip-components=1']
    copy: no
    owner: "{{ item.key }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ factorio.users }}"
  
